### ISSUE TITLE
Block/Implementation style exercises

### ISSUE THREAD

**Issue by rafaparadela** [scala-exercises/site#117]
Exercises that require longer code blocks should be allowed.
For example when showing how to implement typeclasses a koan style approach may not be appropriate and the user should be able to provide a longer code style impl.

**Comment by dialelo** [comment]
As far as I understand this needs some UX/UI work too, right now we only have exercises with small placeholders as inputs. The block style exercises will need to be written in a textarea, maybe in an embedded editor.

**Comment by raulraja** [comment]
@andyscott @juanpedromoreno @dialelo The backend piece of this issue is currently blocked by completion of #105 #149 and it blocks #153. We need to complete this ASAP in order to show Cats and Shapeless exercises before the Typelevel Summit.

**Comment by raulraja** [comment]
This seems to be no longer a priority and requires a better spec of how those exercises may work.
