### ISSUE TITLE
Create Cats exercises

### ISSUE THREAD

**Issue by rafaparadela** [scala-exercises/site#153]
We should start working on create the library Cats, organize its sections and add some exercises.

**Comment by raulraja** [comment]
Cats exercises may cover...
1. Creating and implementing Typeclass instances (Block style)
2. Functor implicit evidence for some std types (Koan style)
3. Xor ops (Koan style)

**Comment by raulraja** [comment]
Blocked by #182

**Comment by raulraja** [comment]
Done
