### ISSUE TITLE
Consolidate Cats and Scalaz versions

### ISSUE THREAD

**Issue by andyscott** [scala-exercises/site#166]
We should make sure we are using the latest and greatest versions of both of these libraries. IMHO-- we should ideally just use one or the other-- and it seems we're migrating towards Cats.

At the very least, I'd like to adjust the builds so that Scalaz and Cats versions are shared across both `core` and `site`. Maybe common dependencies/versions should be defined in `common/BuildCommon.scala` or `common/Dependencies.scala`?

Thoughts?

**Comment by andyscott** [comment]
@raulraja @rafaparadela @FPerezP

**Comment by raulraja** [comment]
Agreed, though for now we are depending on Scalaz concurrent task because cats lacks a similar type, though there are some initiatives out there trying to fix this.

**Comment by raulraja** [comment]
No longer an issue since the Free stack is target independent and we are using `Future` as target since Play requires that in non blocking controllers.
