### ISSUE TITLE
Shapeless exercises

### ISSUE THREAD

**Issue by FPerezP** [scala-exercises/site#167]
We need a set of exercises about Shapeless so we can show it on our Presentation Demo in TypeLevel Summit.

Having a set of 5 exercises is fair enough for the demo, we'll add more exercises in the future.

**Comment by raulraja** [comment]
Currently blocked by #182

**Comment by andyscott** [comment]
This should no longer be blocked by #182.

**Comment by raulraja** [comment]
This was completed though more exercises will be welcome. Will create separate issues for those.
