### ISSUE TITLE
Re-configure projects structure

### ISSUE THREAD

**Issue by rafaparadela** [scala-exercises/site#176]
We're not able to enable the auto deployment for PRs, since the current structure of the project is not compatible with the existing buildpacks. 
So, under the contexto of this ticket, we should re-configure the structure of the modules, once we have the compiler project (and maybe others) isolated in sonatype.

**Comment by andyscott** [comment]
This is marked as ready, but can't be done until I make some adjustments to enable publishing the compiler projects.

**Comment by andyscott** [comment]
See also: https://github.com/47deg/scala-exercises/pull/226#issuecomment-185931515

**Comment by raulraja** [comment]
This has already been fixed as part of #356 and the reunification once we had a sane SBT config as separate modules
