### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by andyscott** [scala-exercises/site#203]
We need getting started guide for developers:

Some information to include:

- [ ] directory structure overview
- [ ] postgres setup
- [ ] running the app locally

**Comment by dbYoung** [comment]
I made second one.
If somebody wants to PR it. I'll do it.

https://github.com/dbYoung/scala-exercises/

**Comment by dialelo** [comment]
That'd be awesome @dbYoung

**Comment by raulraja** [comment]
Closing this one as it will be included as part of #119
