### ISSUE TITLE
Add a mechanism for converting user input to custom types

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/site#259]
For writing our own exercises and specially for third party libraries' exercises we need a way to specify how to convert an input string from the user to an arbitrary type. Built-in types like `String` or `Int` are supported but we often have exercises like this:

```scala
def anExercise(res0: Xor.Right[String, Int]) = {
  val right: String Xor Int = Xor.Right(42)
  right should be(res0)
}
```

We can't currently convert an user-provided input to a `cats.data.Xor` and we should be able to do so. Same for the every type constructors that cats or other libraries provide.

Another case that we don't handle currently is referring to an identifier, see the following example:

```scala
def anExercise(res0: ?) = {
  val one = 1
  val anotherOne = 1
  (one == res0) should be(true)
}
```

Here, we expect the user to insert `anotherOne`. The problem is that we don't want to treat `res0`'s content as a string but an identifier that will be resolved to the value it refers to at runtime.

@andyscott feel free to split this into separate issues if you think they should be tackled separately.

@raulraja @rafaparadela @juanpedromoreno feel free to add your comments.

**Comment by andyscott** [comment]
Both of these items are addressable. The difference, from what I can tell is that in one case _**(A)**_ you want to leverage types and symbols imported into the file and potentially into the object containing the exercises. In the other, **_(B)_** you want the user to have access to symbols that are local to the exercise's method body.

I strongly suspect I can tackle _**A**_ before the conference. The most obvious solution for this is to capture all imports at all static _(read: package, object, anything that does not get instantiated... so no classes or traits... I made this term up)_ scopes up until the exercise method. When the user input is parsed to a tree and typed, I just just ensure all those imports are present first.

I intend to eventually support **_B_**, but this will require dynamically generating and evaluating a Scala AST with the user's input inserted into the tree for the method. This solution will also work for A; so any work I do to quickly support just A will ultimately get thrown away when I do full support for B.

It's possible, if I push it, that I could get B done in time for the conference. But I'm not sure.

Thoughts? Which route should I take?

**Comment by dialelo** [comment]
> I strongly suspect I can tackle A before the conference. The most obvious solution for this is to capture all imports at all static (read: package, object, anything that does not get instantiated... so no classes or traits... I made this term up) scopes up until the exercise method. When the user input is parsed to a tree and typed, I just just ensure all those imports are present first.

That would make `Xor` available in the current scope but i fail to see how it can help us transform the user-provided string into an arbitrary method argument type. For instance, going back to the original exercise.

```scala
/**
  * An explanation.
  */
def anExercise(res0: Xor.Right[String, Int]) = {
  val right: String Xor Int = Xor.Right(42)
  right should be(res0)
}
```

The user will need to insert the string `"Xor.Right(42)"`, how can we make it an instance of `Xor.Right[String, Int]` before feeding it to the `anExercise` method? Furthermore, we want a way for users to extend the types we can coerce user-provided strings to. I imagine we'll have one or more typeclasses that will allow this, is it even possible?

> I intend to eventually support B, but this will require dynamically generating and evaluating a Scala AST with the user's input inserted into the tree for the method. It's substantially more work and it will also solve the problem of A. Unfortunately, any work I do to quickly support just A will ultimately get thrown away when I do full support for B.

> It's possible, if I push it, that I could get B done in time for the conference. But I'm not sure.

Don't rush it, is not really required for the demo. We are freezing the `master` branch before the conference in order to avoid introducing bugs.

> Thoughts? Which route should I take?

It may make sense to tackle B directly, @raulraja thoughts?

**Comment by raulraja** [comment]
I recall Twitter eval allows interpreting any string as code given the imports are provided, not sure we need to parse the expression into an AST unless that is what they're doing behind the scenes.
https://github.com/twitter/util/blob/develop/util-eval/src/main/scala/com/twitter/util/Eval.scala#L140

They also support the concept of session as far as I can tell which would be great for certain exercises that build upon user input.

**Comment by raulraja** [comment]
@andyscott Regarding A. We need to get user input refering to lib types working.
I tested that if for example I change...
```scala
      ...map { case (arg, tpe) ⇒
        catching(toolbox.parse(arg),
          s"Unable to parse arg $arg") >>= { parsedArg ⇒
        catching(toolbox.eval(Typed(parsedArg, tq"$tpe")),
          s"Unable to evaluate arg $arg as $tpe")
      }}
```
for
```scala
      ...map { case (args, tpe) ⇒
        val arg = s"{ import shapeless._; $args}"
        catching(toolbox.parse(arg),
          s"Unable to parse arg $arg") >>= { parsedArg ⇒
        catching(toolbox.eval(Typed(parsedArg, tq"$tpe")),
          s"Unable to evaluate arg $arg as $tpe")
      }}
```
All the shapeless types immediately work.
For the time being we should allow at the Lib level provide a set of imports that will be evaluated with each lib exercise along with the user input.

We need to get this working now because it's preventing from actually properly testing the UI input when trying to reproduce the user experience completing the exercises.

Let's make this change a high priority.

**Comment by andyscott** [comment]
Will do. I'm in the process of bringing back and rewriting some code from a month ago that addresses this properly.
