### ISSUE TITLE
Include path information in Sections so we can show the GitHub contributors

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/site#340]
The compiler should emit sections along with their original path in the repository so we can query GitHub's API to show the commits and contributors of such file.

**Comment by raulraja** [comment]
I presume since we can already render contributors and now we are moving to compile time fetching of contributors this may be closed.

**Comment by rafaparadela** [comment]
Confirmed: We can close this issue due to the reason you mentioned. More info at #390
