### ISSUE TITLE
Add emoji support to the list of contributions

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/site#346]
In the following example, the `:fire:` commit message should be rendered as the :fire: emoji.

![contributions](https://cloud.githubusercontent.com/assets/409039/15290849/5283fa4c-1b7b-11e6-9db8-98072a8ed3a2.png)

**Comment by raulraja** [comment]
I believe this has been addressed in #383. @dialelo feel free to reopen if not

**Comment by rafaparadela** [comment]
Confirmed: https://github.com/scala-exercises/site/pull/383 closes this issue
