### ISSUE TITLE
Evaluation failing because of missing deps

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/site#380]
Getting this with latest master and trying the cats exercises:

@dialelo is this because we don't have scala test in the classpath now that content is a separate module?
@MasseGuillaume this may look familiar since it comes from the evaluator
```
Compilation error: compilation error missing or invalid dependency detected while loading class file 'MonoidSection.class'. Could not access type Assertion in package org.scalatest.package, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'MonoidSection.class' was 
```

**Comment by MasseGuillaume** [comment]
is scalatest on the classpath at runtime ?

https://github.com/scala-exercises/site/blob/master/build.sbt#L113 it look like it's only available at compile time

**Comment by MasseGuillaume** [comment]
:fireworks: best lucks for the launch
