### ISSUE TITLE
Fetch contributions to sections during compilation

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/site#389]

**Comment by raulraja** [comment]
For reference the rationale is becuase we can get easily rate limited by Github... 

Failed invoking get with status : 403, body : 
 {"message":"API rate limit exceeded for 23.20.108.104. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
