### ISSUE TITLE
Library colors

### ISSUE THREAD

**Issue by rafaparadela** [scala-exercises/site#392]
We need to set more proper color to libraries. Israel suggestions are:

![http://cdn.scala.run/j1I.png](http://cdn.scala.run/j1I.png)

**Comment by raulraja** [comment]
Let's give those a try

**Comment by rafaparadela** [comment]
Closed by:
- https://github.com/scala-exercises/exercises-cats/pull/7
- https://github.com/scala-exercises/exercises-shapeless/pull/6
- https://github.com/scala-exercises/exercises-stdlib/pull/8
