### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/site#395]
We need a page to show when the server may be down because of planned maintenance.

**Comment by raulraja** [comment]
Once the page is aviable we can reuse the layout for an Error page and place them in S3 poinitng heroku to them like so:
```bash
heroku config:set \
  ERROR_PAGE_URL=//s3.amazonaws.com/<your_bucket>/your_error_page.html \
  MAINTENANCE_PAGE_URL=//s3.amazonaws.com/<your_bucket>/your_maintenance_page.html
```

**Comment by rafaparadela** [comment]
@raulraja An initial approach:

- Maintenance: http://codepen.io/rafaparadela/pen/rLemLN?editors=1100
- Not found: http://codepen.io/rafaparadela/pen/aZNWoO?editors=1100

Look good to you?

**Comment by raulraja** [comment]
LGTM

**Comment by rafaparadela** [comment]
Done!
- Right now: http://www.scala-exercises.org/
- Maintenance: http://scala-exercises.s3-eu-west-1.amazonaws.com/maintenance.html
- Error: http://scala-exercises.s3-eu-west-1.amazonaws.com/error.html
