### ISSUE TITLE
New S3 bucket

### ISSUE THREAD

**Issue by rafaparadela** [scala-exercises/site#400]
We need having a bucket of AWS S3 in order to host several `html` & `images` resources. The main purpose is provide custom [error pages](https://devcenter.heroku.com/articles/error-pages#create-and-store-the-custom-pages) in Scala Exercises.

Related issue: https://github.com/scala-exercises/site/issues/395

**Comment by FPerezP** [comment]
@rafaparadela It has been created. Please check that it works as expected. Thanks.

**Comment by rafaparadela** [comment]
@FPerezP It's working fine:

http://scala-exercises.s3-eu-west-1.amazonaws.com/bg.jpg

Thank you.
